### ISSUE TITLE
jsplumb在Vue 支持跨组件拖拽么

### ISSUE THREAD

**Issue by Jessiejy** [wangyu142857/flow-chart#3]
如果把想要拖拽的源和目标区域分到两个组件里，报TypeError: Cannot read property '_katavorioDrag' of null 。同样的格式放到同个组件就没问题。求个思路嘤嘤嘤

**Comment by Jessiejy** [comment]
大佬看到可以加我微信嘛？240569178，感谢感谢

**Comment by wangyu142857** [comment]
好几个月没看这个了，这个错应该是组件还没渲染完成的时候执行报错的吧

**Comment by xly544892660** [comment]
最后是怎么解决的呢？

**Comment by huali-dong** [comment]
想要问一下楼主最后解决了吗
